# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    saps-catalog:
      repo: 'https://github.com/EOSC-synergy/saps-catalog'
      branch: develop

sqa_criteria:
   qc_style:
     repos:
       saps-catalog:
         container: catalog-testing
         commands:
           - mvn -f /saps-catalog-repo/pom.xml spotless:check
   qc_coverage:
     repos:
       saps-catalog:
         container: catalog-testing
         commands:
           - mvn -f /saps-catalog-repo/pom.xml -B -DskipTests clean package
           - mvn -f /saps-catalog-repo/pom.xml test
